In [1]:
with open('input1.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1218570


In [3]:
print(text[:1000])

خُذْ في البُكَا إنّ الخَليطَ مُقَوِّضُ
فمُصَرِّحٌ بِفِراقِهِمْ ومُعَرِّضُ
وأَذِبْ فُؤَادَكَ فَالنَّصيرُ على النَّوَى
عَينٌ تَفيضُ ومُهجةٌ تتفضَّضُ
هَاتيكَ أَحْدَاجٌ تُشَدُّ وهَذهِ
أطْنَابُ أخْبِيةٍ تُحَلُّ وتُنْقَضُ
وورَاءَ عيسِهِمُ المُنَاخَةُ عُصْبةٌ
أكْبادُهُم وهُمُ وقُوفٌ تركُضُ
وقفُوا وأَحْشَاءُ الضَّمَائِرِ بالأسَى
تُحشَى وأوْعيةُ المَدَامِعِ تَنْفُضُ
يَتَخافتُونَ ضَنىً فَمُطْلِقُ أَنَّةٍ
ومُطَامِنٌ من زفرةٍ ومُخَفِّضُ
قبضُوا بأَيدِيهِمْ علَى أكبادِهِمْ
والشَّوقُ ينزِعُ من يدٍ ما تَقبِضُ
فإذَا هُمُ أَمِنُوا المُرَاقِبَ صَرَّحُوا
بِشَكاتِهِمْ وإنْ اسْتَرابُوا أعْرَضُوا
رَحَلُوا وآراءُ البُكَاةِ ورَاءَهُمْ
شَتَّى فَسَافِحُ عَبْرَةٍ ومُغيّضُ
أتْبَعْتُهُمْ نَفَساً ودَمْعاً نَارُ ذا
يشْوي الرِّياضَ وماءُ ذَاكَ يُروّضُ
مَنْ نَاشِدٌ لي بالعَقِيقِ حُشَاشةً
طَاحَتْ ورَاءَ الرَّكبِ سَاعةَ قَوَّضُوا
لمْ تَلْوِ راجِعَةً ولَمْ تلْحَقْ بِهِمْ
حتَّى وَهَتْ ممّا تُطيحُ وتنهَضُ
أَتُرَى رُمَاتُهُمُ درَوا مَنْ أوغَلُوا
في قَلبِهِ تلْكَ السِّهَامَ وخَضْخضُوا
يا قَدْ رَضِيتُ بِمَا أَرَاقُوا مِنْ دَمِ

In [4]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(' '.join(chars))
print(vocab_size)


   ! : ، ؟ ء آ أ ؤ إ ئ ا ب ة ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ـ ف ق ك ل م ن ه و ى ي ً ٌ ٍ َ ُ ِ ّ ْ
51


In [5]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("مرحبا يا جماعة"))
print(decode(encode("مرحبا يا جماعة")))

[37, 22, 18, 13, 12, 1, 42, 12, 1, 17, 37, 12, 30, 14]
مرحبا يا جماعة


In [6]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1218570]) torch.int64
tensor([19, 47, 21, 50,  1, 33, 42,  1, 12, 36, 13, 47, 35, 46, 12,  1, 10, 38,
        49,  1, 12, 36, 19, 46, 36, 42, 28, 46,  1, 37, 47, 34, 46, 40, 49, 48,
        27, 47,  0, 33, 37, 47, 26, 46, 22, 49, 48, 18, 44,  1, 13, 48, 33, 48,
        22, 12, 34, 48, 39, 48, 37, 50,  1, 40, 37, 47, 30, 46, 22, 49, 48, 27,
        47,  0, 40,  8, 46, 21, 48, 13, 50,  1, 33, 47,  9, 46, 12, 20, 46, 35,
        46,  1, 33, 46, 12, 36, 38, 49, 46, 26, 42, 22, 47,  1, 30, 36, 41,  1,
        12, 36, 38, 49, 46, 40, 46, 41,  0, 30, 46, 42, 38, 44,  1, 15, 46, 33,
        42, 27, 47,  1, 40, 37, 47, 39, 17, 14, 44,  1, 15, 15, 33, 27, 49, 46,
        27, 47,  0, 39, 46, 12, 15, 42, 35, 46,  1,  8, 46, 18, 50, 20, 46, 12,
        17, 44,  1, 15, 47, 25, 46, 20, 49, 47,  1, 40, 39, 46, 21, 39, 48,  0,
         8, 28, 50, 38, 46, 12, 13, 47,  1,  8, 19, 50, 13, 48, 42, 14, 45,  1,
        15, 47, 18, 46, 36, 49, 47,  1, 40, 15, 47, 38, 50, 34, 46, 27, 47,  0,
      

In [7]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [8]:
block_size = 8
train_data[:block_size + 1]

tensor([19, 47, 21, 50,  1, 33, 42,  1, 12])

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]
for t in range(block_size):
    context = x[:t + 1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([19]) the target: 47
when input is tensor([19, 47]) the target: 21
when input is tensor([19, 47, 21]) the target: 50
when input is tensor([19, 47, 21, 50]) the target: 1
when input is tensor([19, 47, 21, 50,  1]) the target: 33
when input is tensor([19, 47, 21, 50,  1, 33]) the target: 42
when input is tensor([19, 47, 21, 50,  1, 33, 42]) the target: 1
when input is tensor([19, 47, 21, 50,  1, 33, 42,  1]) the target: 12


In [10]:
batch_size = 4
ix = torch.randint(len(data) - block_size, (batch_size,))
ix

tensor([1146171,  682413, 1095183,  822916])

In [11]:
[data[i:i+block_size] for i in ix]

[tensor([37, 12, 30, 14,  0, 42, 15, 13]),
 tensor([30, 46, 36, 41,  1, 12, 36, 38]),
 tensor([42,  6, 45,  1, 33, 42,  1, 12]),
 tensor([15, 48,  1, 12, 36, 18, 46, 27])]

In [12]:
[data[i+1:i+block_size+1] for i in ix]

[tensor([12, 30, 14,  0, 42, 15, 13, 12]),
 tensor([46, 36, 41,  1, 12, 36, 38, 46]),
 tensor([ 6, 45,  1, 33, 42,  1, 12, 36]),
 tensor([48,  1, 12, 36, 18, 46, 27, 12])]

In [13]:
torch.randint?

In [14]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i + block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('-----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t + 1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} the target: {target}")
        # print(decode(context.tolist()))

inputs:
torch.Size([4, 8])
tensor([[41,  1, 33, 12, 22, 48, 24, 45],
        [ 0, 37, 48, 38,  1, 33, 46, 40],
        [27, 46, 22, 49, 46, 14, 44,  1],
        [46,  1,  8, 46, 28,  0, 39, 46]])
targets:
torch.Size([4, 8])
tensor([[ 1, 33, 12, 22, 48, 24, 45,  0],
        [37, 48, 38,  1, 33, 46, 40, 34],
        [46, 22, 49, 46, 14, 44,  1, 37],
        [ 1,  8, 46, 28,  0, 39, 46, 22]])
-----
when input is [41] the target: 1
when input is [41, 1] the target: 33
when input is [41, 1, 33] the target: 12
when input is [41, 1, 33, 12] the target: 22
when input is [41, 1, 33, 12, 22] the target: 48
when input is [41, 1, 33, 12, 22, 48] the target: 24
when input is [41, 1, 33, 12, 22, 48, 24] the target: 45
when input is [41, 1, 33, 12, 22, 48, 24, 45] the target: 0
when input is [0] the target: 37
when input is [0, 37] the target: 48
when input is [0, 37, 48] the target: 38
when input is [0, 37, 48, 38] the target: 1
when input is [0, 37, 48, 38, 1] the target: 33
when input is [0, 37, 4

In [15]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, idx, targets=None):
        
        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B, T, C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)
            
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indicies in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            
            # focus only on the last time step
            logits = logits[:, -1, :] # become(B, C)
            
            # apply softmax to get probabilities
            props = F.softmax(logits, dim=-1) # (B, C)
            
            #sample from the distribution
            idx_next = torch.multinomial(props, num_samples=1) # (B, 1)
            
            #append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
            
        return idx
    
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

torch.Size([32, 51])
tensor(4.8628, grad_fn=<NllLossBackward0>)


In [16]:
print(decode(m.generate(torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


ر:؟ًذَئُبّ :تَب!آةغْافؤشلزبفربخئقإ:نضةئَزضٍ ِذذـ
أبب!قدط!وح
كشزر:ّنلُفً؟ز
ؤّذُْإغقصٍىحٍ:جئآجٍطىسمنظظ


In [17]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(10000):
    # sample a batch of data
    xb, yb = get_batch('train')
    
    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
print(loss.item())

2.4230005741119385


In [19]:
print(decode(m.generate(torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


لَوَهاجخَتَلَّلَها
وبوالانامرالَتَرَ كارَحُهِعَدَد أَنَتَرولسِهُ
أَفي عَسَلوَياتَائِ بِ اكُعِ
موالَو


# Mathmatical Trick in self-attention

In [20]:
B,T,C = 4,8,2
x = torch.randn(B,T,C)

In [21]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [22]:
x[0]

tensor([[ 1.5885, -1.6396],
        [-0.3891,  1.1815],
        [ 1.1251,  0.3572],
        [-1.5154, -0.0753],
        [-1.1910,  0.1151],
        [-0.9640, -0.2058],
        [-0.0294,  0.8635],
        [-0.3365, -0.0604]])

In [23]:
xbow[0]

tensor([[ 1.5885, -1.6396],
        [ 0.5997, -0.2291],
        [ 0.7748, -0.0336],
        [ 0.2023, -0.0440],
        [-0.0764, -0.0122],
        [-0.2243, -0.0445],
        [-0.1965,  0.0852],
        [-0.2140,  0.0670]])

In [24]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b

print('a=')
print(a)
print('----')
print('b=')
print(b)
print('----')
print('c=')
print(c)


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
----
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
----
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


## Version 2

In [25]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [26]:
xbow2 = wei @ x # (B, T, T) @ (B, T, C) --> (B, T, C)
torch.allclose(xbow, xbow2)

True

## version 3: use softmax

In [27]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf')) # the future (tokens) can be communicating to the past
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

## version 4: self-attention

In [28]:
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) --> (B, T, T)

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [29]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [30]:
n = 19
for k in range(n //4, 0, -1):
    print(k+1)

5
4
3
2
